@criptoAPI_HostAddress = http://localhost:5168
Accept: application/json

###  Encrypt 
POST {{criptoAPI_HostAddress}}/api/encrypt
Content-Type: application/json

{
  "message": "curioso",
  "key": "secreto"
}

###

### Decrypt 
POST {{criptoAPI_HostAddress}}/api/decrypt
Content-Type: application/json

{
  "message": "00010000000100000001000100011011000010100000011100000000",
  "key": "secreto"
}

###