@criptoAPI_HostAddress = http://localhost:5168
Accept: application/json

###  Encrypt 
POST {{criptoAPI_HostAddress}}/api/encrypt
Content-Type: application/json

{
  "message": "mariana",
  "key": "secreto"
}

###

### Decrypt 
POST {{criptoAPI_HostAddress}}/api/decrypt
Content-Type: application/json

{
  "message": "\u001E\u0004\u0011\u001B\u0004\u001A\u000E",
  "key": "secreto"
}

###